const INSTRUMENTS = [
  {
    id: "violin",
    name: "Violin",
    family: "Strings",
    tags: ["portable", "classical", "melodic", "ensemble"],
    description: "A bright, expressive instrument that shines in orchestras and small groups.",
    beginnerFit: "Great if you enjoy precision, expressive melodies, and learning posture + bowing.",
  },
  {
    id: "guitar",
    name: "Guitar",
    family: "Strings",
    tags: ["portable", "versatile", "songwriting", "popular"],
    description: "A flexible instrument for pop, rock, folk, and solo performances.",
    beginnerFit: "Perfect for songwriters and anyone who wants quick progress with chords.",
  },
  {
    id: "cello",
    name: "Cello",
    family: "Strings",
    tags: ["warm", "classical", "expressive", "ensemble"],
    description: "A rich, deep sound used in orchestras and cinematic music.",
    beginnerFit: "Wonderful if you love warm tones and are okay with a larger instrument.",
  },
  {
    id: "flute",
    name: "Flute",
    family: "Winds",
    tags: ["bright", "light", "classical", "portable"],
    description: "A clear, airy sound that stands out in bands and orchestras.",
    beginnerFit: "Great for players who enjoy breath control and quick melodic lines.",
  },
  {
    id: "clarinet",
    name: "Clarinet",
    family: "Winds",
    tags: ["warm", "versatile", "band", "jazzy"],
    description: "Smooth and flexible, used in bands, jazz, and orchestras.",
    beginnerFit: "A solid choice if you want a warm tone and many genre options.",
  },
  {
    id: "saxophone",
    name: "Saxophone",
    family: "Winds",
    tags: ["jazzy", "bold", "band", "solo"],
    description: "A bold instrument with a big sound for jazz, pop, and pep bands.",
    beginnerFit: "Best for confident players who like being heard.",
  },
  {
    id: "trumpet",
    name: "Trumpet",
    family: "Brass",
    tags: ["bright", "bold", "marching", "band"],
    description: "Brilliant and powerful, perfect for fanfares and band features.",
    beginnerFit: "Awesome for energetic players who enjoy high impact sounds.",
  },
  {
    id: "trombone",
    name: "Trombone",
    family: "Brass",
    tags: ["bold", "low", "band", "jazz"],
    description: "Warm, strong low tones with a unique slide for pitch control.",
    beginnerFit: "Good if you like strong low sounds and playful glissandos.",
  },
  {
    id: "french-horn",
    name: "French Horn",
    family: "Brass",
    tags: ["warm", "orchestral", "heroic", "ensemble"],
    description: "A mellow, heroic tone used for cinematic lines and rich harmonies.",
    beginnerFit: "Great for focused players who want a lush orchestral sound.",
  },
  {
    id: "drums",
    name: "Drum Kit",
    family: "Percussion",
    tags: ["rhythm", "energetic", "band", "perform"],
    description: "The heartbeat of a band, great for rhythm and coordination.",
    beginnerFit: "Ideal if you have lots of energy and love keeping the beat.",
  },
  {
    id: "marimba",
    name: "Marimba",
    family: "Percussion",
    tags: ["melodic", "warm", "ensemble", "classical"],
    description: "A melodic percussion instrument with a warm, wooden sound.",
    beginnerFit: "Perfect for students who like percussion but want melodies too.",
  },
  {
    id: "snare",
    name: "Snare Drum",
    family: "Percussion",
    tags: ["rhythm", "marching", "tight", "energetic"],
    description: "A sharp, crisp drum used in marching bands and ensembles.",
    beginnerFit: "Good for players who like precision and marching rhythms.",
  },
  {
    id: "piano",
    name: "Piano/Keyboard",
    family: "Keys",
    tags: ["versatile", "solo", "songwriting", "foundation"],
    description: "A foundational instrument for melody, harmony, and composition.",
    beginnerFit: "Great if you want to understand music theory and play many styles.",
  },
];

const QUESTIONS = [
  {
    id: "family",
    title: "Which family feels most exciting?",
    subtitle: "Choose the sound world you want to explore first.",
    type: "single",
    options: [
      { value: "Strings", label: "Strings", note: "Warm, expressive, bowing or plucking", weights: { Strings: 4 } },
      { value: "Winds", label: "Woodwinds", note: "Breath-driven, smooth or bright", weights: { Winds: 4 } },
      { value: "Brass", label: "Brass", note: "Bold, powerful, heroic sounds", weights: { Brass: 4 } },
      { value: "Percussion", label: "Percussion", note: "Rhythmic, energetic, physical", weights: { Percussion: 4 } },
      { value: "Keys", label: "Keys", note: "Piano or keyboard styles", weights: { Keys: 4 } },
      { value: "open", label: "Not sure yet", note: "Show me a mix", weights: { mix: 2 } },
    ],
  },
  {
    id: "style",
    title: "Which music vibe fits you most?",
    subtitle: "Your style helps us pick the right tone.",
    type: "single",
    options: [
      { value: "classical", label: "Classical / orchestral", note: "Elegant, cinematic, detailed", weights: { classical: 3, ensemble: 2 } },
      { value: "popular", label: "Pop / rock / indie", note: "Modern, upbeat, catchy", weights: { popular: 3, versatile: 2 } },
      { value: "jazz", label: "Jazz / blues", note: "Groove, improv, bold lines", weights: { jazzy: 3, solo: 2 } },
      { value: "marching", label: "Marching / pep band", note: "Energy, precision, loud", weights: { marching: 3, rhythm: 2 } },
      { value: "film", label: "Film / game scores", note: "Big sound, emotional", weights: { cinematic: 3, ensemble: 2 } },
    ],
  },
  {
    id: "energy",
    title: "How much energy do you want while playing?",
    subtitle: "Think about physical movement and volume.",
    type: "single",
    options: [
      { value: "chill", label: "Calm and focused", note: "Precision, control, detail", weights: { warm: 2, expressive: 2 } },
      { value: "balanced", label: "A mix of calm and energy", note: "Versatile and adaptable", weights: { versatile: 2, melodic: 1 } },
      { value: "high", label: "High energy", note: "Powerful, loud, physical", weights: { bold: 2, energetic: 3, rhythm: 2 } },
    ],
  },
  {
    id: "role",
    title: "Which role sounds most fun?",
    subtitle: "Think about how you want to show up in a group.",
    type: "single",
    options: [
      { value: "lead", label: "Carry the melody", note: "Solo lines and spotlight moments", weights: { melodic: 3, solo: 2 } },
      { value: "support", label: "Support the harmony", note: "Blend with others", weights: { ensemble: 3, warm: 1 } },
      { value: "rhythm", label: "Drive the rhythm", note: "Keep the groove going", weights: { rhythm: 3 } },
      { value: "foundation", label: "Build songs", note: "Chords and structure", weights: { songwriting: 3, foundation: 2 } },
    ],
  },
  {
    id: "practice",
    title: "How do you like to practice?",
    subtitle: "Pick what sounds most like you.",
    type: "single",
    options: [
      { value: "short", label: "Short focused sessions", note: "Small goals, big progress", weights: { portable: 2, melodic: 1 } },
      { value: "long", label: "Long deep practice", note: "Build stamina and technique", weights: { classical: 2, expressive: 2 } },
      { value: "creative", label: "Try new things each day", note: "Improvising and experimenting", weights: { jazzy: 2, versatile: 2 } },
    ],
  },
  {
    id: "space",
    title: "Where will you play most often?",
    subtitle: "This affects size and volume.",
    type: "single",
    options: [
      { value: "bedroom", label: "At home / bedroom", note: "Quiet, manageable volume", weights: { portable: 2, warm: 1 } },
      { value: "school", label: "School band / orchestra", note: "Group rehearsals", weights: { ensemble: 2, band: 2 } },
      { value: "stage", label: "On stage / performances", note: "Big sound, confident", weights: { perform: 2, bold: 2 } },
    ],
  },
];

const SCORE_TAGS = {
  Strings: "Strings",
  Winds: "Winds",
  Brass: "Brass",
  Percussion: "Percussion",
  Keys: "Keys",
};

const SONG_LIBRARY = {
  Strings: [
    { title: "Spring", creator: "Antonio Vivaldi", mood: "Bright + classical" },
    { title: "Canon in D", creator: "Johann Pachelbel", mood: "Warm + flowing" },
    { title: "A Thousand Years", creator: "Christina Perri", mood: "Emotional + lyrical" },
  ],
  Winds: [
    { title: "Rhapsody in Blue (opening)", creator: "George Gershwin", mood: "Smooth + bold" },
    { title: "My Favorite Things", creator: "Richard Rodgers", mood: "Light + playful" },
    { title: "Careless Whisper", creator: "George Michael", mood: "Soulful + smooth" },
  ],
  Brass: [
    { title: "Fanfare for the Common Man", creator: "Aaron Copland", mood: "Heroic + powerful" },
    { title: "Sir Duke", creator: "Stevie Wonder", mood: "Funky + joyful" },
    { title: "Uptown Funk", creator: "Mark Ronson ft. Bruno Mars", mood: "Bold + energetic" },
  ],
  Percussion: [
    { title: "We Will Rock You", creator: "Queen", mood: "Stompy + iconic" },
    { title: "Billie Jean", creator: "Michael Jackson", mood: "Groovy + tight" },
    { title: "Eye of the Tiger", creator: "Survivor", mood: "High-energy" },
  ],
  Keys: [
    { title: "Clair de Lune", creator: "Claude Debussy", mood: "Dreamy + soft" },
    { title: "Let It Be", creator: "The Beatles", mood: "Warm + singable" },
    { title: "River Flows in You", creator: "Yiruma", mood: "Emotional + flowing" },
  ],
};
